# Scikit-learn 中的 Scalar

In [1]:
import numpy as np
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X[:10, :]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

## scikit-learn 中的 StandardScaler

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
standard_scaler = StandardScaler()

In [8]:
standard_scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [9]:
standard_scaler.mean_

array([5.83416667, 3.08666667, 3.70833333, 1.17      ])

In [10]:
standard_scaler.scale_

array([0.81019502, 0.44327067, 1.76401924, 0.75317107])

In [11]:
X_train = standard_scaler.transform(X_train)
X_train[:5, :]

array([[-0.90616043,  0.93246262, -1.30856471, -1.28788802],
       [-1.15301457, -0.19551636, -1.30856471, -1.28788802],
       [-0.16559799, -0.64670795,  0.22203084,  0.17260355],
       [ 0.45153738,  0.70686683,  0.95898425,  1.50032315],
       [-0.90616043, -1.32349533, -0.40154513, -0.09294037]])

In [12]:
X_test_standard = standard_scaler.transform(X_test)
X_test_standard[:5, :]

array([[-0.28902506, -0.19551636,  0.44878573,  0.43814747],
       [-0.04217092, -0.64670795,  0.78891808,  1.63309511],
       [-1.0295875 , -1.77468693, -0.23147896, -0.22571233],
       [-0.04217092, -0.87230374,  0.78891808,  0.96923531],
       [-1.52329579,  0.03007944, -1.25187599, -1.28788802]])

In [13]:
from sklearn.neighbors import KNeighborsClassifier

In [14]:
knn_clf = KNeighborsClassifier(n_neighbors=3)

In [15]:
knn_clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [16]:
knn_clf.score(X_test_standard, y_test)

1.0

In [17]:
knn_clf.score(X_test, y_test)

0.3333333333333333

## 实现我们自己的 StandardScaler

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [19]:
from playML.preprocessing import StandardScaler
standard_scaler = StandardScaler()
standard_scaler.fit(X_train)

In [20]:
X_train = standard_scaler.transform(X_train)
X_test_standard = standard_scaler.transform(X_test)

In [21]:
knn_clf = KNeighborsClassifier(n_neighbors=3)
knn_clf.fit(X_train, y_train)
knn_clf.score(X_test_standard, y_test)

1.0